### PR TITLE
Support for Swift 2.3

### PR DESCRIPTION
**Pull request by hartbit**
I guess this probably requires an upstream Swift 2.3 branch.

### CODE REVIEW

**Comment by patchthecode** [comment]
This has many conflicts. Cannot merge.
What I will be doing however, is creating  swift 3 branch.

**Comment by patchthecode** [comment]
This one had too much changes that was different. So I jumped straight to swift 3 instead of 2.3 on another branch.

**Comment by hartbit** [comment]
How about Swift 2.3? Users of the library who need to build with Xcode 8 but can't afford to go directly to Swift 3 will be stuck.

**Comment by patchthecode** [comment]
Hmm... youre right.. ok ok.
i'll do 2.3

**Comment by patchthecode** [comment]
Ok. I won't be able to handle this.
Its getting too much.
Is it possible you create a separate branch called `Swift2.3` and send a pull request there instead of master branch? I will merge the changes if you do.

**Comment by patchthecode** [comment]
Some one has asked the same thing, and i suggested the same thing i just said to you.

here--> https://github.com/patchthecode/JTAppleCalendar/issues/144

So I guess who ever does it first.

**Pull request closed without merging**
