### PR TITLE
Rename UIScrollViewDelegate methods

### PR DESCRIPTION
**Pull request by dbmrq**

### CODE REVIEW

**Comment by dbmrq** [comment]
I'm making these Pos, but you can take them as suggestions, feel free to ignore them if you think it's better. It's just easier to open PRs than to discuss every little thing in issues, then you can decide if you merge them or not.

**Comment by patchthecode** [comment]
Heh. you're late.
Already merged

**Comment by patchthecode** [comment]
The renamed version makes more sense.
Btw, its sad youre not listed as a contributor --> https://github.com/patchthecode/JTAppleCalendar/graphs/contributors

I think for it to show up there you have to confirm your github email or something like that

**Comment by dbmrq** [comment]
Haha, cool. I'll keep going through the files and you can decide what you want to merge. :)

**Comment by patchthecode** [comment]
OK nevermind. My mistake. It will show up if you make updates to master (default branch)

**Comment by patchthecode** [comment]
And yea sure. Im almost done with the new documentation

**Comment by dbmrq** [comment]
Ah, that's ok. I'll get there when this code makes it to master then. :)

**Comment by patchthecode** [comment]
Why revert it?

**Comment by dbmrq** [comment]
Yes, but you have to declare them according to the UIScrollViewDelegate protocol for them to be called.

**Comment by patchthecode** [comment]
yes i just re-looked it and realized. I merged it.
ok then.

**Comment by patchthecode** [comment]
Btw, do you think its stable enough?
I really want to get swift3 out.

**Comment by dbmrq** [comment]
Well, since there are so many breaking changes this would have to be a major version, so I think it's best to make an official release only when you're 100% sure the API won't change for a while. Before doing that I think it would be good to go through every exposed method and property and see if the names can be improved and make sure they stick to the new guidelines. I don't know if you did that already. But even before doing that people can use it. I will. You can even publish it or merge it, I just think it's best to be absolutely sure before tagging it version 6 and releasing. Before that you can just say something like "the current version at the master branch (if you merge) will be released as version 6 soon, you can use it already, but the API may change, so keep an eye out".

**Comment by patchthecode** [comment]
Makes sense. I think i'll do that.
Merge to master, and leave a notice

**Pull request merged**
