### PR TITLE
Carthage support.

### PR DESCRIPTION
**Pull request by aboudou**
Hello,

This pull request is about issue #1140 and add Carthage support to JTAppleCalendar.

You may have to edit bundle id from JTAppleCalendar.xcodeproj to set the correct informations.

### CODE REVIEW

**Comment by patchthecode** [comment]
Thanks will take a look after work

**Comment by patchthecode** [comment]
merged.

**Comment by patchthecode** [comment]
I had one question.
what do i have to put in my Cartfile to use this pull?

someone was experiencing this issue https://github.com/patchthecode/JTAppleCalendar/issues/1159

When I tried it my self by putting following in the cart file, I also got the same error
```
github "patchthecode/JTAppleCalendar"  ~> 8.0.2 
```

Did i merge it incorrectly?

**Comment by aboudou** [comment]
Hello,

The merge is correct, but won't be available until you make another release (Carthage use tag name for the version).

To test on the master branch, you may use :

github "patchthecode/JTAppleCalendar" "master"

**Comment by patchthecode** [comment]
thanks so much for the explanation.
I'll explain this to him, and i'll also tag a new release soon.
thanks again!

**Comment by aboudou** [comment]
You're welcome :)

**Pull request merged**
