### PR TITLE
Add Tailor and clear warnings

### PR DESCRIPTION
**Pull request by dbmrq**
Phew! That was a lot of work.

I used Tailor because swiftlint doesn't support Swift 3 yet. All you have to do is `brew install tailor` and you'll get Tailor's warnings after Xcode builds.

For now I just used the basic rules and the line length rule set to 78 characters.

I broke the lines so that they remain within that limit, but although that makes most of the code a lot more readable, there are a few edge cases where it looks pretty bad. I think it's still a good idea to constrain it to 78 characters, though (you can set a guide column at Xcode's preferences, it's really useful). Most of the problems happen when the code is too indented, so there's very little workable space. And, well, that just shouldn't happen. If the code is shifted to the right so much that you can't fit a single method name, that code needs refactoring. That's a lot more work, though, and we should do it little by little, so for now I just broke the lines. It gets pretty obvious where it needs changes, which is good. When we find a [pyramid of doom](https://en.wikipedia.org/wiki/Pyramid_of_doom_(programming)) we should think about how to refactor that code so that doesn't happen.

I also didn't add many other rules yet, like the function length rule, I think that should be the next one. It's related to the last problem and it would require a lot of refactoring too. There are functions in the code that are more than 100 lines long, that can't happen, we have to split them in more specific functions. Now that I'm getting more familiar with your code I can help little by little.

There's also the name length rule, I think we should restrain construct's names to something like 30 characters, which is already a lot, but there are many functions and variables that go beyond that. Stuff like `setupMonthInfoDataForStartAndEndDate`… which could be something like `setupMonthData(for startDate: Date, endDate: Date…`. Maybe I'm missing something, but why cram all that in `DateConfigParameters`? At first glance it just seems to make things less intuitive, I looked at that and thought "DateConfigParameters? What the hell is that?". While `setupMonthData(for startDate: Date` is a lot friendlier. Anyway, that's just an example, and I can help with all that if you want me to, I just didn't want to start changing everything without even discussing. I didn't even really look at how most of the code works, these are just a few impressions, but maybe there are reasons for things being as they are. So far my changes were mostly just in the style. By the way, it's probably still not perfect, there were a lot of things to change and I have to go to bed, haha. But I'll keep working on it.

And, well, there are other rules and best practices we can implement little by little, that's enough for now I guess, haha.

I tested these changes in the demo app for a bit and everything seems good, but still you should try it out too just to make sure. I don't know what's the future of this `DynamicGeneration` branch, but we should have a sort of a scratch branch just to test stuff before merging with the rest.

### CODE REVIEW

**Comment by patchthecode** [comment]
OK. will look it up in the morning. Heading to sleep now.
Btw i'm [currently in the process](https://patchthecode.github.io/) of better documentation like you suggested. Still work in progress.

**Comment by patchthecode** [comment]
OK, i'm still going through it.
But one thing to note -> I think that for Swift3, the convention for enums is that the `cases` should start with a lower case letter, rather than an upper case letter

**Comment by dbmrq** [comment]
Oh, you're right, I didn't know about that! Sorry.
I'll fix it tonight and make another PR then.


Em qui, 6 de out de 2016 às 12:34, JTAppleCalendar <notifications@github.com>
escreveu:

**Comment by dbmrq** [comment]
Well, we could change it to 100 characters, it's finr by me, but like I said I think less than 80 turns out to be good, because it also calls the atention to other problems, like too many nested levels. IMO the example you used is one that should be refactored. And 80 characters is pretty canonical, which I like. But we can increase it if you want.

**Comment by dbmrq** [comment]
(I was referring to your second example. The first I do think is too long anyway, I don't see why not break it. And no matter what line length you pick, even 100 or more, there'll always be cases like this, where you think "oh, if we just had one more character.)

**Comment by patchthecode** [comment]
Ah, i see what you mean.
Concerning the deep nested problems, then ok, lets leave the limit how it is right now. Because yes, i do know that I have to make the code more neat. So leave the limit for now.
But just change the small case for enums

**Comment by dbmrq** [comment]
Cool, I'll make another PR when I get back home. :)

**Pull request closed without merging**
