### PR TITLE
Fix for #1165

### PR DESCRIPTION
**Pull request by diegorozen**

### CODE REVIEW

**Comment by diegorozen** [comment]
@patchthecode Any comments or additional thing needed here?

**Comment by RobertMietelski** [comment]
I have the same bug, this pull request fixes it. Please merge this branch.

**Comment by mixo44** [comment]
Please accept this PR, I have the same issue.

**Comment by patchthecode** [comment]
I have to make sure this doesnt break the other modes..
the problem is, these days, time is hard to come by

**Review by patchthecode — APPROVED** [review]

**Comment by patchthecode** [comment]
way over due...  life/time/smh

**Pull request merged**
