### PR TITLE
Added comparer functions

### PR DESCRIPTION
**Pull request by bmoliveira**
Due to Xcode 8.1 compilation errors comparing Date with Date!

### CODE REVIEW

**Comment by patchthecode** [comment]
Hey just a question. I have XCode 8, but I do not have this issue.
Can you explain a little more what error happens when you compare Date with Date! ?

**Comment by bmoliveira** [comment]
Do you have the GM release of 8.1? With the 8.0 I didn't had any problem but now in the new version was giving compilation errors with compare Date with Date!

**Comment by patchthecode** [comment]
Ah thank you.
I will download 8.1 now and merge this.

**Comment by r-dent** [comment]
I have the same problem right now. does anyone know what is causing this? Why are the comapartors suddenly missing?

**Comment by patchthecode** [comment]
Yes. This is a bug in XCode 8.1 
https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html

They said the following:

>When using generics and implicitly-unwrapped optionals, type inference can fail to unwrap the optional leading to compiler errors for valid code. (28621624)

>As a workaround, explicitly unwrap the optional. For example, in the following valid code, the compiler gives an error because u is implicitly-unwrapped in the return statement.

This is now fixed on master branch.
I'll release version 6.0.1 in about 30 mins

**Comment by patchthecode** [comment]
Ok guys the fix is done.
I tried pushing the new version, but CocoaPods have a bug.
I have filed a bug report with them here --> https://github.com/CocoaPods/CocoaPods/issues/6098

So you cant update ☹️ 

As a work around, you can use Master Branch in your pod file:

`pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'`
The do a `pod install`

**Comment by patchthecode** [comment]
Issue resolved.
6.0.1 has been released

**Comment by r-dent** [comment]
Thanks for the quick reaction!

**Comment by patchthecode** [comment]
@r-dent thanks. If this lib has helped you in any way, freel free to leave a star rating. Thanks! :]

**Pull request merged**
