### PR TITLE
Code improvement (safe capture list, early exits)

### PR DESCRIPTION
**Pull request by yyaremenko**
I hope this version is of a slightly improved readability + some best practices implemented

### CODE REVIEW

**Comment by patchthecode** [comment]
I had to revert this change. It was not building with swift3 master branch.

**Comment by yyaremenko** [comment]
@patchthecode weird; will do that fix locally first (not in browser, as I did before), run tests and make another pull request

thanks

**Comment by patchthecode** [comment]
@yyaremenko cool. BTW, if this library has been very useful to you, consider leaving a star rating 👍

**Comment by yyaremenko** [comment]
@patchthecode I would like to ask you some questions regarding tests, if you don't mind:

1) iOS tests file is named:
     JTAppleCalendar_iOSTests.swift 
though the testing class name is:
    JTAppleCalendar_tvOSTests
I guess this is a bug? should I fix this?

2) is there a reason why you use absolutely identical code lines in JTAppleCalendar_iOSTests.swift, in testConfigurationParametersDefaultBehaviorssFirst()
    lines 165-173 == lines 176-184 == lines 187-195
I mean, it's not that I try to criticize the code, I just can't get the point - maybe there's a special meaning for that

3) Also, if you don't mind, I would suggest using something like DataProvider - as long as testConfigurationParametersDefaultBehaviorssFirst() repeatedly uses very same logics, only changing actual / expected parameters - please see example in my code
https://github.com/yyaremenko/swift_event_dispatcher/blob/master/DBEventDispatcherTests/DBEventDispatcherTests.swift line 75

4) I did not find any tests checking if cellState.selectedPosition (the part of code I proposed the fix to) - so if you don't mind maybe I'll add some tests (btw looks like I've found a bug here - in my project after I select a range of dates second time, the cellState.selectedPosition returns wrong values)

**Comment by patchthecode** [comment]
Test has just been added. Currently only two things are tested. The other test functions are added for just to improve statistics. But I am modifying them to their correct functions gradually. tvOS tests and iOS tests currently look the same because they are just copy and paste of each other. This will all be fixed in the coming weeks. I am working on them locally for now.

Concerning the `rangeSelection` bug you found can you tell me the steps to repeat it using the sample app?

**Comment by patchthecode** [comment]
BTW, thank you for all your observations. very helpful.

**Comment by yyaremenko** [comment]
well actually the bug was found on 5.0.1; I'll check once more - because maybe it was actually my bug

probably I'll write tests for that to make sure the bug is there; here are the steps:

- set allowsMultipleSelection of the calendar view to true

- select range of dates: calendarView.selectDates(from: dateA, to: dateB)
everything works fine here

- on user select a date beyond that range:
-- re-select (programmatically) currently selected date (to actually de-select it)
-- re-select (programmatically) the date from previously selected range which is closest to user's selected date (to actually de-select it)
everything looks fine on this step

- now, select (programmatically) range of dates starting (and including) user's selected date to (including) closest date of previously selected range
on this level, the bug occurs:
-- user's selected date has .full value
-- all other dates, except the last one, have .right value
-- the last date has .middle value

here is the controller code:
http://pastebin.com/te4TGj1y
(the link will expire in a week)

**Comment by yyaremenko** [comment]
@patchthecode regarding tests - so, may I use DataProvider for some of iOS tests? and throw away repeating code lines? you didn't reply to me regarding that question )

**Comment by patchthecode** [comment]
@yyaremenko concerning the tests, yes, you can use a dataProvider and throw away some of the tests.  To more help i can get on this project the better.

**Comment by patchthecode** [comment]
@yyaremenko and concerning your bug, i'll have to look at it in the morning. Will look at it tomorrow

**Comment by yyaremenko** [comment]
@patchthecode looks I won't leave you alone for today ) I just can't get the clue of how did your test passed before: testConfigurationParametersDefaultBehaviorssFirst()

you create  the very identical structure ConfigurationParameters each new 'set' of tests, and you expect to get -different- number of rows each time, and... you actually get that -different- number of rows?... could you please give me a hint of what I'm missing here?

**Comment by patchthecode** [comment]
@yyaremenko 
It goes like this
1. I made some tests to meet a requirement on my end.
2. I needed to meet a certain number of tests, but I didnt have time to write tests because I am busy writing code.
3. So i just made copies of the first tests,and changed their names. I also changed the value I am expecting (and yes, this makes no sense logically) so that the tests will not be copies of each other.

While this makes no sense logically, It does make sense in that it meets my requirement. I now have a certain number of tests that are not copies of each other.

This is the reason I am hesitant to remove the tests now. Because I need a certain number to fulfill a requirement.

**Comment by yyaremenko** [comment]
@patchthecode  uh oh didn't know the number of test itself is crucial... could you please check if my changes are ok to you (as I reduced the number of tests considerably by removing duplicates and implementing data providers)?

https://github.com/yyaremenko/JTAppleCalendar/commit/9194a1d302b032353c61c45c2eb2aad229ff9e46

**Comment by patchthecode** [comment]
hmm.. it now does not meet the requirement. But do not worry, we can leave it like this.

The test count only matters upon release of the next version. 6.1+
By the timr 6.1+ needs to be release i would have found a solution with the test count issue from my end. So do not worry about it.

**Comment by yyaremenko** [comment]
@patchthecode  great, thanks! please accept my pull request https://github.com/patchthecode/JTAppleCalendar/pull/242

**Pull request merged**
