### PR TITLE
Updated to compile and test under Xcode 8 beta 6

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by patchthecode** [comment]
will merge in a bit.
currently in the midst of a huge code change.

**Comment by patchthecode** [comment]
One thing however. Since the changes I am working on are so huge, it might not be possible to merge this smoothly. The changes you have done may have to be reapplied.

**Comment by hartbit** [comment]
Are you working with Xcode 8 beta 6?

**Comment by patchthecode** [comment]
No the changes are being done on master branch for Xcode 7. For swift 2.

Therefore, when I port the changes over to the swift 3 branch for XCode 8 beta 6, it will have conflicts with the changes you have done here. Your changes are too many, so it can be resolved however. But i'm just letting you know in case you have more changes.

**Comment by hartbit** [comment]
When your work on the master branch in finished, send me a message and I can handle the Swift 3 conversion if you want. :)

**Comment by patchthecode** [comment]
OK. my workplace all migrated to swift 3 last week so i was forced to convert it myself.
The latest code feature i'm currently working on is on the `DynamicGeneration` branch.
It has the final massive upgrade. This library will be finished after I finish testing it. So the swift3 conversion is done.  The code on that branch is still a bit buggy. It should be finished real soon.

**Pull request closed without merging**
