### PR TITLE
Merging master into FixingScrolls

### PR DESCRIPTION
**Pull request by mgurreta**
@patchthecode do you mind merging master into FixingScrolls so I can get the latest fixes from master?

During the merge back I only found conflicts in the following file:
`Sources/UIScrollViewDelegates.swift`

It looks accurate to me (based on #754), but do you mind double-checking?

Thanks

### CODE REVIEW

**Comment by mgurreta** [comment]
@patchthecode this is just updating `FixingScrolls` with the latest code from `master`.

**Comment by mgurreta** [comment]
@patchthecode do you think you can merge this PR?

Thanks!

**Comment by patchthecode** [comment]
Hey, the next released version of this will will include the scroll fixes
ok.
I looked at your merge, and i had some local changes that will be different.
However, i do understand that you want your branch to contain the fixes on
master. I'll take a look.

just a lil tied up. Currently Im @ the hospital. #NewDad! 😁
Will look at your merge request

**Comment by mgurreta** [comment]
Oohhhhh maaannn!!!!! CONGRATULATIONS!! 

Of course you don't have to waste a second of your time with this freaking PR!!!

You know what? I'll close it! 

I'll wait for the next release, I'm pretty sure your changes are much better of what FixingScroll is offering right now!

please enjoy your paternity! and Salud! 

Cheers!

**Pull request closed without merging**
