### PR TITLE
Update JTCalendarProtocols

### PR DESCRIPTION
**Pull request by hatunike**
I'm pretty sure this is the only change required for swift 2.3 support. I haven't really done anything other than make this one change. Because my existing project is a swift 2.3 and I just came across this project. I saw #85 and #144.

### CODE REVIEW

**Comment by hatunike** [comment]
Looks like I naively considered the work needed for this. I'm guessing I also need to fix the example app and project settings. It's not too much work, i'll see if I can get to it. As far as the pod goes, it's pretty minor though.

**Comment by hatunike** [comment]
It works but I had failing tests not sure why, I've been busy customizing my calendar :)

**Comment by patchthecode** [comment]
Ok. I have finished the updates im working. Will merge this as soon as im done testing. Your tests are failing in Travis because.... I do not know how to setup tests there :( .. I have to do more reading up on this, or maybe someone can help. 
I should be done testing soon.

**Comment by bcorrea2-luizalabs** [comment]
cool, @patchthecode will you generate a new tag?

**Pull request merged**
