### PR TITLE
Fix didScrollToDateSegmentWith not called when dragging

### PR DESCRIPTION
**Pull request by LucasR93**
Hi,

I experienced an issue with the `didScrollToDateSegmentWith` delegate in my current setup. 
I am using a single line calendar with bounce disabled (infinite scrolling)
The method is not called, when the user drags the calendar strip, because the scrollview is never decelerating. 
I added a new delegate method called 
```swift
func calendar(_ calendar: JTAppleCalendarView, didDragToDateSegmentWith visibleDates: DateSegmentInfo)
``` 
that closes this gap. In the UIScrollviewDelegate I implemented the `scrollViewDidEndDragging ` method and I check for `willDecelerate`. Only if `willDecelerate` is false, the user actually dragged and released the touch at a fixed position, otherwise we continue and `didScrollToDateSegmentWith` is called after finishing animating.

### CODE REVIEW

**Comment by LucasR93** [comment]
Fails on some test, I don't know why, library is working though

**Comment by patchthecode** [comment]
Yea dont worry about the tests.
I have to update those.
I've been so busy creating the library that I have slacked a bit on the tests.
I'll look at your problem/solution over the weekend.

**Comment by LucasR93** [comment]
Hi, did you find the time to look at it? Should we improve something?

**Comment by patchthecode** [comment]
finally got the time to look at this.
Only thing i will change is 

```swift
    public func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        // Only call the delegate, when not decelerating
        // otherwise, didScrollToDateSegmentWith is called
        // after finishing animation
        if !decelerate {
            visibleDates {[unowned self] dates in
                self.calendarDelegate?.calendar(self, didScrollToDateSegmentWith: dates) // I will change this
            }
        }
    }
```

I will change the code above and not introduce a new function since i think the developer. let me know what you think.

**Pull request closed without merging**
