### PR TITLE
Added missing return to functionIsUnsafeSafeToRun in scrollToSegment

### PR DESCRIPTION
**Pull request by HKisd**

### CODE REVIEW

**Comment by patchthecode** [comment]
Hi. can you let me know the problem this fixed?

**Comment by HKisd** [comment]
I have a button which calls scrolltosegment(.next)
Quickly pressing the button many times causes whole app to freeze and cpu
usage to stay at 100%.
As you can see without return if functionIsUnsafeToRun it is both queued
and immediately run. This is clearly wrong behavior.

Adding return fixes freezing.

There are also couple other places in the same file where
functionIsUnsafeToRun is checked and in those functions return is called.

**Comment by patchthecode** [comment]
alright. will test this soon once im free.
then i'll mege.

**Comment by patchthecode** [comment]
fixed.
other changes were added aswell

**Pull request closed without merging**
