### PR TITLE
fixed animation bug when reload dates

### PR DESCRIPTION
**Pull request by Sibcat**
additional fix to #136

### CODE REVIEW

**Comment by Sibcat** [comment]
sorry, my mistake - "attempt to add identical layout attributes to list of on screen attributes to animated"

**Comment by patchthecode** [comment]
So, basically youre saying it is adding the same indexPath twice? :/

**Comment by Sibcat** [comment]
i think it's not; seems it does not handle situations like 
```swift
let date = NSDate()
calendarView.reloadDate([date, date])
```

**Comment by patchthecode** [comment]
I see. So basically since same date is being reloaded twice, It therefore adds the same indexPath twice. 
And since the same index path is added twice, then the animation errors happens. I get it now.
Ok here's what the fix should be.

**Comment by patchthecode** [comment]
This fix is for the swift3 version. Do you know how to convert it to swift2?
If yes, then do the conversion, and I will merge the code.
If not, then I will do the merge in the morning.

**Comment by Sibcat** [comment]
i'm not sure how to convert it
better do it in the morning

**Comment by patchthecode** [comment]
Ok. Scratch that. 
Change the code inside the function to this 

```swift
        var paths = [IndexPath]()
        for date in dates {
            let aPath = pathsFromDates([date])
            
            if aPath.count > 0 && !paths.contains(aPath[0]) {
                paths.append(aPath[0])
                let cellState = cellStateFromIndexPath(aPath[0])
                if let validCounterPartCell = indexPathOfdateCellCounterPart(date, indexPath: aPath[0], dateOwner: cellState.dateBelongsTo) {
                    paths.append(validCounterPartCell)
                }
            }
        }
        batchReloadIndexPaths(paths)
```

**Comment by patchthecode** [comment]
If its fixed then create a pull request.

**Comment by patchthecode** [comment]
I'm off to sleep. Will read your results in the morning.

**Comment by Sibcat** [comment]
its fixed, thanks!

**Pull request closed without merging**
