### PR TITLE
Memory leaks fixed. Formatting improved.

### PR DESCRIPTION
**Pull request by gmoraleda**
First of all, thanks for the great work. I've been using this library and it helped me a lot.
Nevertheless I've been running into memory leaks caused by the calendar view. I quickly went thought all blocks which had strong references to `self` and added modified them with `[weak self]`.

I've been testing it with the modifications and leaks are gone.

I used the chance to run swiftformat (https://github.com/nicklockwood/SwiftFormat) to enforce the swift style guide and get rid of extra spacing, unneeded self, etc.
Also renamed a couple of variables `theData` -> `calendarData`, `theOffset` -> `newOffset`, there is no need to include the article in a variable name.

Thanks for your time again.
Cheers!

### CODE REVIEW

**Comment by patchthecode** [comment]
hmm. I was not aware of any memory leaks in this app.

The was an introduction of two memory leaks on starting on version 8.0.0

Screen Shot 2019-09-06 at 10 54 13 AM

But this has since been fixed in version 8.0.1

Did you by chance have the leaks on version 8.0.0 ?

**Comment by gmoraleda** [comment]
Mmm, I need to double-check that on Monday (I don't have access to the project till then).
But nevertheless there are still blocks in `8.0.1` using strong `self` in dispatch queues (e.g. `JTACMonthActionFunctions.swift`).

That code will be scheduled and executed whether or not that object is still alive, meaning that `self` will be retained till then (more info here: https://stackoverflow.com/a/21988407/4473187).

**Comment by patchthecode** [comment]
Hmm. 
I am not sure that calling self inside of a closure will cause a retain cycle.

There are a number of places in the library where I do thing like this -->
```swift
DispatchQueue.main.async {
   self.something()
}
```

To my knowledge, this will not cause retain cycles because, the closure is not _owned_ by the class. I guess we can talk again once  you can check your project. I highly suspect the retain cycle was from version 8.0.0 and not 8.0.1. Lets see 🍻

**Comment by patchthecode** [comment]
for reference --> https://stablekernel.com/how-to-prevent-memory-leaks-in-swift-closures/

**Comment by gmoraleda** [comment]
That's an interesting topic, Paul Hudson [suggests](https://www.hackingwithswift.com/read/9/4/back-to-the-main-thread-dispatchqueuemain) to use weak self also in GCD... 🤷‍♂

**Comment by patchthecode** [comment]
Interesting. I guess the main reason why he did this was to be safe and that there is no harm in doing it to be safe as seen in the screenshot below.

Screen Shot 2019-09-07 at 10 51 22 AM


Its not a bad practice i guess, but in our case, it really should not cause a leak. 
Let me know (once you get the chance) if the leak was from version 8.0.0

If you were using version 8.0.1, then i'll have to go leak hunting xD

**Comment by gmoraleda** [comment]
Version confirmed. We were using `8.0.0`, we need to find a solution to integrate `8.0.1` since we are no using Xcode 11 yet 🤔 
I'm closing the PR.

Nevertheless you may want to take a look at swiftformat, you can run it as a run scrip during build phase or via command line. It's super fast and makes sure that the project has a consistent formatting.

Thanks again.

**Comment by patchthecode** [comment]
i'll take aa look. thanks.

**Comment by cluno-moraleda** [comment]
We are hosting the Podspec file for `8.0.1` under https://github.com/cluno-engineering/Specs.git
So anyone interested in continue using JTAppleCalendar via Cocoapods can use that spec as long as they add the repo to their configuration:
`pod repo add cluno-specs https://github.com/cluno-engineering/Specs.git`

In the Podfile you would need to specify the version and the source:

```
...
source 'https://github.com/cluno-engineering/Specs.git'
platform :ios, '11.0'
...

 pod 'JTAppleCalendar', '8.0.1'
```

**Comment by patchthecode** [comment]
you did it?

One of the reasons why i have cocoa pods removed was because i didnt know how to re-merge it into the project. I tried every configuration and it was not working on my end. I also tried to look for many tutorials on how to re-add it to my project. 

I was of the impression that I had to do file changes, but it looks like you did it with just  that podspec file. Would you mind doing a pull request? I just didnt have more time to invest into learning cocoapods to get it working.

**Comment by patchthecode** [comment]
This clearly shows my lack of understanding on cocoapods...

**Comment by cluno-moraleda** [comment]
Well, we didn't do much. Downloaded the latest podspec from Cocoapods: https://raw.githubusercontent.com/CocoaPods/Specs/1a5e5dc616914491f19921db79a0d96741136b36/Specs/4/0/b/JTAppleCalendar/8.0.0/JTAppleCalendar.podspec.json

Updated the version to `8.0.1` and then run:
```
pod spec lint
pod repo push master (in our case was cluno-engineering instead of master) JTAppleCalendar.podspec.json
```  

if you have any issues you can add the `--verbose` flag and check the output.

**Comment by cluno-moraleda** [comment]
@patchthecode, any luck here?

**Comment by patchthecode** [comment]
yes, i got tied up this week with work.
I'll look this up over the weekend. I should have positive results by then. Sorry for the late response.

**Comment by patchthecode** [comment]
I just had time to look at this.
I am a little confused.
Just few questions. One I know the answers to these, i can write proper instructions for people still wanting to use cocoapods.

1. Do i need to put a copy of your JtappleCalendar.podspec.json in my repository? and at which path in my repository? (if the path matters)
2. What does someone need to put in their podfile to download this lib in their project?

**Comment by gmoraleda** [comment]
If you want to support Cocoapods directly you should be able to push into the master repository (as you did before). So you would need to update the podspec file to the version 8.0.1 (or use the one we are hosting) and run the commands I wrote above.

The file can be anywhere (no need to have it on the JTAppleCalendar repo), can be deleted after being pushed to Cocoapods.

If that doesn't work, you could use our Podspec repo:

1. Add cluno repo to your local installation:
```pod repo add cluno-specs https://github.com/cluno-engineering/Specs.git```
2. Modify the Podfile adding the new source to look into our repo for podspecs:
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cluno-engineering/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '11.0'

target 'YOUR_PROJECT' do
    pod 'JTAppleCalendar', '8.0.1'

...
```

**Comment by patchthecode** [comment]
thanks for the help.
I think i got cocoapods back in again.

**Comment by gmoraleda** [comment]
Glad to hear! Good job! 💪

**Pull request closed without merging**
